### ISSUE TITLE
What are the limitations of QEMU in Proxmox when it comes to running MacOS 9.2.2?

### ISSUE THREAD

**Issue by TyrfingMjolnir** [ThomasLamprecht/qemu-server#1]
What are the limitations of QEMU in Proxmox when it comes to running MacOS 9.2.2?

Is QEMU in Proxmox able to do what I do in this ASCIInema: https://asciinema.org/a/223107 ?

**Comment by ThomasLamprecht** [comment]
See the docs for how to get (official) help/support for Proxmox VE: https://pve.proxmox.com/pve-docs/pve-admin-guide.html#getting_help
